AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
