version: 2

jobs:
  ruby-2.6.9:
    docker:
      - image: circleci/ruby:2.6.9
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec fasterer
      - run: bundle exec mdl README.md CHANGELOG.md
  ruby-2.7.5:
    docker:
      - image: circleci/ruby:2.7.5
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec fasterer
      - run: bundle exec mdl README.md CHANGELOG.md
  ruby-3.0.3:
    docker:
      - image: circleci/ruby:3.0.3
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec fasterer
      - run: bundle exec mdl README.md CHANGELOG.md

workflows:
  version: 2
  tests:
    jobs:
      - ruby-2.6.9
      - ruby-2.7.5
      - ruby-3.0.3
