version: 2

jobs:
  ruby-2.6.8:
    docker:
      - image: circleci/ruby:2.6.8
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec fasterer
      - run: bundle exec mdl README.md CHANGELOG.md
  ruby-2.7.4:
    docker:
      - image: circleci/ruby:2.7.4
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec fasterer
      - run: bundle exec mdl README.md CHANGELOG.md
  ruby-3.0.2:
    docker:
      - image: circleci/ruby:3.0.2
    steps:
      - checkout
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - run: bundle install
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec fasterer
      - run: bundle exec mdl README.md CHANGELOG.md

workflows:
  version: 2
  tests:
    jobs:
      - ruby-2.6.8
      - ruby-2.7.4
      - ruby-3.0.2
