name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 6"

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - "3.0"
          - 3.1
#          - head
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - run: rm Gemfile.lock
      - run: rm .ruby-version
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec appraisal install || true
      - run: bundle exec appraisal rake
      - run: bundle exec standardrb
      - run: bundle exec fasterer
